//
//  OddsPresenter.swift
//  Wager
//
//  Created by Emrecan OZTURK on 31.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OddsPresentationLogic {
    func presentOdds(response: Odds.Models.Response)
    func presentFailure(message: String)
}

class OddsPresenter: OddsPresentationLogic {
    weak var viewController: OddsDisplayLogic?
  
    // MARK: Do something
  
    func presentOdds(response: Odds.Models.Response) {
        let viewModel = Odds.Models.ViewModel(model: response.model)
        viewController?.displayOdds(viewModel: viewModel)
    }
    
    func presentFailure(message: String) {
        viewController?.displayFailure(message: message)
    }
}
