//
//  OddsViewController.swift
//  Wager
//
//  Created by Emrecan OZTURK on 31.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OddsDisplayLogic: AnyObject {
    func displayOdds(viewModel: Odds.Models.ViewModel)
    func displayFailure(message: String)
}

class OddsViewController: UIViewController, OddsDisplayLogic {
    var interactor: OddsBusinessLogic?
    var router: (NSObjectProtocol & OddsRoutingLogic & OddsDataPassing)?

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = OddsInteractor()
        let presenter = OddsPresenter()
        let router = OddsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        getOdds()
    }
  
    // MARK: Do something
  
    //@IBOutlet weak var nameTextField: UITextField!
  
    func getOdds() {
        let request = Odds.Models.Request(sportsKey: "")
        interactor?.getOdds(request: request)
    }
  
    func displayOdds(viewModel: Odds.Models.ViewModel) {
        
    }
    
    func displayFailure(message: String) {
        showAlert(withTitle: "Ops!", withMessage: message)
    }
}
