//
//  OddsWorker.swift
//  Wager
//
//  Created by Emrecan OZTURK on 31.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias callbackOddsSuccess = (_ response: Odds.Models.Response) ->()

class OddsWorker {
    func getOdds(sportsKey: String, successCallBack: @escaping callbackOddsSuccess, failure: @escaping callbackFailure) {
        SportsNetworkManager().getOdds(sportsKey: sportsKey) { response in
            successCallBack(Odds.Models.Response.init(model: response))
        } failure: { error in
            failure(error)
        }
    }
}
