//
//  OddsInteractor.swift
//  Wager
//
//  Created by Emrecan OZTURK on 31.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OddsBusinessLogic {
    func getOdds(request: Odds.Models.Request)
}

protocol OddsDataStore {
    var sportsKey: String { get set }
}

class OddsInteractor: OddsBusinessLogic, OddsDataStore {
    
    var presenter: OddsPresentationLogic?
    var worker: OddsWorker?
    var sportsKey: String = ""
  
    // MARK: Do something
  
    func getOdds(request: Odds.Models.Request) {
        worker = OddsWorker()
        worker?.getOdds(sportsKey: request.sportsKey, successCallBack: { [weak self] odds in
            guard let self = self else { return }
            self.presenter?.presentOdds(response: odds)
        }, failure: { [weak self] message in
            guard let self = self else { return }
            self.presenter?.presentFailure(message: message.localizedDescription)
        })
    }
    
}
