//
//  OddsModels.swift
//  Wager
//
//  Created by Emrecan OZTURK on 31.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Odds {
    // MARK: Use cases
  
    enum Models {
        struct Request {
            var sportsKey: String
        }
        struct Response {
            var model: [OddsModel]?
        }
        struct ViewModel {
            var model: [OddsModel]?
        }
    }
}
