//
//  EventsInteractor.swift
//  Wager
//
//  Created by Emrecan OZTURK on 31.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventsBusinessLogic {
    func getSports(request: Events.Models.Request)
}

protocol EventsDataStore {
    var sportsKey: String { get set }
}

class EventsInteractor: EventsBusinessLogic, EventsDataStore {
    var sportsKey: String = ""
    
    var presenter: EventsPresentationLogic?
    var worker: EventsWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func getSports(request: Events.Models.Request) {
        worker = EventsWorker()
        worker?.getSports(successCallBack: { [weak self] sports in
            guard let self = self else { return }
            self.presenter?.presentSports(response: sports)
        }, failure: { [weak self] error in
            guard let self = self else { return }
            self.presenter?.presentFailure(message: error.localizedDescription)
        })
    }
}
