//
//  EventsPresenter.swift
//  Wager
//
//  Created by Emrecan OZTURK on 31.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventsPresentationLogic {
    func presentSports(response: Events.Models.Response)
    func presentFailure(message: String)
}

class EventsPresenter: EventsPresentationLogic {
    weak var viewController: EventsDisplayLogic?
  
    // MARK: Do something
  
    func presentSports(response: Events.Models.Response) {
        let viewModel = Events.Models.ViewModel(model: response.model)
        viewController?.displaySports(viewModel: viewModel)
    }
    
    func presentFailure(message: String) {
        viewController?.displayFailure(message: message)
    }
}
