//
//  EventsWorker.swift
//  Wager
//
//  Created by Emrecan OZTURK on 31.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias callbackSportsSuccess = (_ response: Events.Models.Response) ->()
typealias callbackFailure       = (_ response: Error) ->()

class EventsWorker {
    func getSports(successCallBack: @escaping callbackSportsSuccess, failure: @escaping callbackFailure) {
        SportsNetworkManager().getSports { sports in
            successCallBack(Events.Models.Response.init(model: sports))
        } failure: { error in
            failure(error)
        }
    }
}
